#############################################################################
# Makefile for building: libCheatSh.so
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  cheatsh.pro
# Template: lib
# Command: /usr/bin/qmake -o Makefile cheatsh.pro CONFIG+=release KSYNTAXHIGHLIGHTING_LIB_DIR=/usr/lib KSYNTAXHIGHLIGHTING_INCLUDE_DIR=/usr/include/KF5/KSyntaxHighlighting IDE_SOURCE_TREE=/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0 IDE_BUILD_TREE=/home/uni/projects/3rdparties/qt-creator-opensource-4.14.0-x64-build
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DCHEATSH_LIBRARY -DGIT_VERSION=\"1.1.0\" -D'RELATIVE_PLUGIN_PATH="../lib/qtcreator/plugins"' -D'RELATIVE_LIBEXEC_PATH="../libexec/qtcreator"' -D'RELATIVE_DATA_PATH="../share/qtcreator"' -D'RELATIVE_DOC_PATH="../share/doc/qtcreator"' -DIDE_LIBRARY_BASENAME=\"lib\" -DQT_CREATOR -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_CAST_TO_ASCII -DQT_RESTRICTED_CAST_FROM_ASCII -DQT_DISABLE_DEPRECATED_BEFORE=0x050900 -DQT_USE_QSTRINGBUILDER -DQT_NO_DEBUG -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -fvisibility=hidden -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -Wno-noexcept-type -O2 -std=gnu++1z -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -IANSIEsc2HTML/src -I../3rdparties/qt-creator-opensource-4.14.0-x64-build/src -I../3rdparties/qt-creator-opensource-src-4.14.0/src -I../3rdparties/qt-creator-opensource-src-4.14.0/src/libs -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/tools -I../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins -I../3rdparties/qt-creator-opensource-src-4.14.0/src/libs -I../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/3rdparty -I/usr/include/KF5/KSyntaxHighlighting -I. -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtConcurrent -I/usr/include/qt/QtCore -I.moc/release-shared -I.uic -I/usr/lib/qt/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = CheatSh4.14.0
DISTDIR = /home/uni/projects/cheatsh-qtcreator/.obj/release-shared/CheatSh4.14.0
LINK          = g++
LFLAGS        = -Wl,-z,origin -Wl,-rpath,/usr/lib -Wl,-z,origin '-Wl,-rpath,$$ORIGIN:$$ORIGIN/../:$$ORIGIN/.' -Wl,--no-undefined -Wl,-O1 -shared -Wl,-soname,libCheatSh.so
LIBS          = $(SUBLIBS) -L/home/uni/projects/cheatsh-qtcreator/ANSIEsc2HTML/build -lANSIEsc2HTML_static -L/home/uni/projects/3rdparties/qt-creator-opensource-4.14.0-x64-build/lib/qtcreator -L/home/uni/projects/3rdparties/qt-creator-opensource-4.14.0-x64-build/lib/qtcreator/plugins -lCore -L/usr/lib -lKF5SyntaxHighlighting -lTextEditor -lAggregation -lExtensionSystem -lUtils -L/home/uni/.local/share/data/QtProject/qtcreator/plugins/4.14.0 /usr/lib/libQt5Widgets.so /usr/lib/libQt5Gui.so /usr/lib/libQt5Network.so /usr/lib/libQt5Concurrent.so /usr/lib/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = .obj/release-shared/

####### Files

SOURCES       = cheatshplugin.cpp \
		cheatoutputplane.cpp \
		cheatfilter.cpp \
		optionspage.cpp \
		progressreport.cpp \
		querymanager.cpp \
		settings.cpp \
		optionsdialog.cpp \
		updatechecker.cpp .rcc/qrc_cheatsh_unix.cpp \
		.moc/release-shared/moc_cheatshplugin.cpp \
		.moc/release-shared/moc_cheatoutputplane.cpp \
		.moc/release-shared/moc_cheatfilter.cpp \
		.moc/release-shared/moc_optionspage.cpp \
		.moc/release-shared/moc_progressreport.cpp \
		.moc/release-shared/moc_querymanager.cpp \
		.moc/release-shared/moc_optionsdialog.cpp \
		.moc/release-shared/moc_updatechecker.cpp
OBJECTS       = .obj/release-shared/cheatshplugin.o \
		.obj/release-shared/cheatoutputplane.o \
		.obj/release-shared/cheatfilter.o \
		.obj/release-shared/optionspage.o \
		.obj/release-shared/progressreport.o \
		.obj/release-shared/querymanager.o \
		.obj/release-shared/settings.o \
		.obj/release-shared/optionsdialog.o \
		.obj/release-shared/updatechecker.o \
		.obj/release-shared/qrc_cheatsh_unix.o \
		.obj/release-shared/moc_cheatshplugin.o \
		.obj/release-shared/moc_cheatoutputplane.o \
		.obj/release-shared/moc_cheatfilter.o \
		.obj/release-shared/moc_optionspage.o \
		.obj/release-shared/moc_progressreport.o \
		.obj/release-shared/moc_querymanager.o \
		.obj/release-shared/moc_optionsdialog.o \
		.obj/release-shared/moc_updatechecker.o
DIST          = CMakeLists.txt \
		CheatSh.json.in \
		/usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_Attica.pri \
		/usr/lib/qt/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/qt/mkspecs/modules/qt_BluezQt.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivitiesStats.pri \
		/usr/lib/qt/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuthCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCddb.pri \
		/usr/lib/qt/mkspecs/modules/qt_KChart.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KContacts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDESu.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KFileMetaData.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGantt.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHolidays.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHtml.pri \
		/usr/lib/qt/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJS.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJSApi.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuffCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt/mkspecs/modules/qt_KParts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeople.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeopleWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPlotting.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPty.pri \
		/usr/lib/qt/mkspecs/modules/qt_KRunner.pri \
		/usr/lib/qt/mkspecs/modules/qt_KScreen.pri \
		/usr/lib/qt/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUserFeedbackCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUserFeedbackWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_OktetaCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_OktetaGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/qt/mkspecs/modules/qt_Prison.pri \
		/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		../3rdparties/qt-creator-opensource-src-4.14.0/qtcreator_ide_branding.pri \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/coreplugin_dependencies.pri \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/shared/syntax/syntax_shared.pri \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/texteditor/texteditor_dependencies.pri \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/aggregation/aggregation_dependencies.pri \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/extensionsystem/extensionsystem_dependencies.pri \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/utils_dependencies.pri \
		../3rdparties/qt-creator-opensource-src-4.14.0/qtcreator.pri \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/rpath.pri \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/qtcreatorplugin.pri \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/unix/hide_symbols.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources_functions.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		cheatsh.pro cheatshplugin.h \
		cheatsh_global.h \
		cheatshconstants.h \
		cheatoutputplane.h \
		cheatfilter.h \
		optionspage.h \
		progressreport.h \
		querymanager.h \
		settings.h \
		optionsdialog.h \
		updatechecker.h cheatshplugin.cpp \
		cheatoutputplane.cpp \
		cheatfilter.cpp \
		optionspage.cpp \
		progressreport.cpp \
		querymanager.cpp \
		settings.cpp \
		optionsdialog.cpp \
		updatechecker.cpp
QMAKE_TARGET  = CheatSh
DESTDIR       = ../../.local/share/data/QtProject/qtcreator/plugins/4.14.0/
TARGET        = libCheatSh.so
TARGETD       = libCheatSh.so


first: all
####### Build rules

../../.local/share/data/QtProject/qtcreator/plugins/4.14.0/libCheatSh.so: ANSIEsc2HTML cheatsh_ru.qm .uic/ui_optionsdialog.h $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	@test -d ../../.local/share/data/QtProject/qtcreator/plugins/4.14.0/ || mkdir -p ../../.local/share/data/QtProject/qtcreator/plugins/4.14.0/
	-$(DEL_FILE) $(TARGET)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-$(MOVE) $(TARGET) ../../.local/share/data/QtProject/qtcreator/plugins/4.14.0/$(TARGET)



Makefile: cheatsh.pro /usr/lib/qt/mkspecs/linux-g++/qmake.conf /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_Attica.pri \
		/usr/lib/qt/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/qt/mkspecs/modules/qt_BluezQt.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivitiesStats.pri \
		/usr/lib/qt/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuthCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCddb.pri \
		/usr/lib/qt/mkspecs/modules/qt_KChart.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KContacts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDESu.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KFileMetaData.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGantt.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHolidays.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHtml.pri \
		/usr/lib/qt/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJS.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJSApi.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuffCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt/mkspecs/modules/qt_KParts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeople.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeopleWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPlotting.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPty.pri \
		/usr/lib/qt/mkspecs/modules/qt_KRunner.pri \
		/usr/lib/qt/mkspecs/modules/qt_KScreen.pri \
		/usr/lib/qt/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUserFeedbackCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUserFeedbackWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_OktetaCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_OktetaGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/qt/mkspecs/modules/qt_Prison.pri \
		/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		../3rdparties/qt-creator-opensource-src-4.14.0/qtcreator_ide_branding.pri \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/coreplugin_dependencies.pri \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/shared/syntax/syntax_shared.pri \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/texteditor/texteditor_dependencies.pri \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/aggregation/aggregation_dependencies.pri \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/extensionsystem/extensionsystem_dependencies.pri \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/utils_dependencies.pri \
		../3rdparties/qt-creator-opensource-src-4.14.0/qtcreator.pri \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/rpath.pri \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/qtcreatorplugin.pri \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/unix/hide_symbols.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources_functions.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		cheatsh.pro \
		CheatSh.json.in \
		cheatsh_unix.qrc
	$(QMAKE) -o Makefile cheatsh.pro CONFIG+=release KSYNTAXHIGHLIGHTING_LIB_DIR=/usr/lib KSYNTAXHIGHLIGHTING_INCLUDE_DIR=/usr/include/KF5/KSyntaxHighlighting IDE_SOURCE_TREE=/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0 IDE_BUILD_TREE=/home/uni/projects/3rdparties/qt-creator-opensource-4.14.0-x64-build
/usr/lib/qt/mkspecs/features/spec_pre.prf:
/usr/lib/qt/mkspecs/common/unix.conf:
/usr/lib/qt/mkspecs/common/linux.conf:
/usr/lib/qt/mkspecs/common/sanitize.conf:
/usr/lib/qt/mkspecs/common/gcc-base.conf:
/usr/lib/qt/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt/mkspecs/common/g++-base.conf:
/usr/lib/qt/mkspecs/common/g++-unix.conf:
/usr/lib/qt/mkspecs/qconfig.pri:
/usr/lib/qt/mkspecs/modules/qt_Attica.pri:
/usr/lib/qt/mkspecs/modules/qt_Baloo.pri:
/usr/lib/qt/mkspecs/modules/qt_BluezQt.pri:
/usr/lib/qt/mkspecs/modules/qt_KActivities.pri:
/usr/lib/qt/mkspecs/modules/qt_KActivitiesStats.pri:
/usr/lib/qt/mkspecs/modules/qt_KArchive.pri:
/usr/lib/qt/mkspecs/modules/qt_KAuth.pri:
/usr/lib/qt/mkspecs/modules/qt_KAuthCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri:
/usr/lib/qt/mkspecs/modules/qt_KCddb.pri:
/usr/lib/qt/mkspecs/modules/qt_KChart.pri:
/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri:
/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri:
/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KContacts.pri:
/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KCrash.pri:
/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri:
/usr/lib/qt/mkspecs/modules/qt_KDESu.pri:
/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri:
/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri:
/usr/lib/qt/mkspecs/modules/qt_KFileMetaData.pri:
/usr/lib/qt/mkspecs/modules/qt_KGantt.pri:
/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri:
/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KHolidays.pri:
/usr/lib/qt/mkspecs/modules/qt_KHtml.pri:
/usr/lib/qt/mkspecs/modules/qt_KI18n.pri:
/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri:
/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri:
/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri:
/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri:
/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KJS.pri:
/usr/lib/qt/mkspecs/modules/qt_KJSApi.pri:
/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri:
/usr/lib/qt/mkspecs/modules/qt_KNewStuffCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri:
/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri:
/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri:
/usr/lib/qt/mkspecs/modules/qt_KParts.pri:
/usr/lib/qt/mkspecs/modules/qt_KPeople.pri:
/usr/lib/qt/mkspecs/modules/qt_KPeopleWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KPlotting.pri:
/usr/lib/qt/mkspecs/modules/qt_KPty.pri:
/usr/lib/qt/mkspecs/modules/qt_KRunner.pri:
/usr/lib/qt/mkspecs/modules/qt_KScreen.pri:
/usr/lib/qt/mkspecs/modules/qt_KService.pri:
/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri:
/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri:
/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri:
/usr/lib/qt/mkspecs/modules/qt_KUserFeedbackCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KUserFeedbackWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KWallet.pri:
/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri:
/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri:
/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri:
/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_pdf.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_pdf_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_script.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_websockets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/lib/qt/mkspecs/modules/qt_OktetaCore.pri:
/usr/lib/qt/mkspecs/modules/qt_OktetaGui.pri:
/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri:
/usr/lib/qt/mkspecs/modules/qt_Prison.pri:
/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_Solid.pri:
/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri:
/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri:
/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri:
/usr/lib/qt/mkspecs/features/qt_functions.prf:
/usr/lib/qt/mkspecs/features/qt_config.prf:
/usr/lib/qt/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/qt/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt/mkspecs/features/toolchain.prf:
/usr/lib/qt/mkspecs/features/default_pre.prf:
../3rdparties/qt-creator-opensource-src-4.14.0/qtcreator_ide_branding.pri:
../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/coreplugin_dependencies.pri:
../3rdparties/qt-creator-opensource-src-4.14.0/src/shared/syntax/syntax_shared.pri:
../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/texteditor/texteditor_dependencies.pri:
../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/aggregation/aggregation_dependencies.pri:
../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/extensionsystem/extensionsystem_dependencies.pri:
../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/utils_dependencies.pri:
../3rdparties/qt-creator-opensource-src-4.14.0/qtcreator.pri:
../3rdparties/qt-creator-opensource-src-4.14.0/src/rpath.pri:
../3rdparties/qt-creator-opensource-src-4.14.0/src/qtcreatorplugin.pri:
/usr/lib/qt/mkspecs/features/resolve_config.prf:
/usr/lib/qt/mkspecs/features/default_post.prf:
/usr/lib/qt/mkspecs/features/unix/hide_symbols.prf:
/usr/lib/qt/mkspecs/features/warn_on.prf:
/usr/lib/qt/mkspecs/features/qt.prf:
/usr/lib/qt/mkspecs/features/resources_functions.prf:
/usr/lib/qt/mkspecs/features/resources.prf:
/usr/lib/qt/mkspecs/features/moc.prf:
/usr/lib/qt/mkspecs/features/unix/opengl.prf:
/usr/lib/qt/mkspecs/features/uic.prf:
/usr/lib/qt/mkspecs/features/unix/thread.prf:
/usr/lib/qt/mkspecs/features/qmake_use.prf:
/usr/lib/qt/mkspecs/features/file_copies.prf:
/usr/lib/qt/mkspecs/features/testcase_targets.prf:
/usr/lib/qt/mkspecs/features/exceptions.prf:
/usr/lib/qt/mkspecs/features/yacc.prf:
/usr/lib/qt/mkspecs/features/lex.prf:
cheatsh.pro:
CheatSh.json.in:
cheatsh_unix.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile cheatsh.pro CONFIG+=release KSYNTAXHIGHLIGHTING_LIB_DIR=/usr/lib KSYNTAXHIGHLIGHTING_INCLUDE_DIR=/usr/include/KF5/KSyntaxHighlighting IDE_SOURCE_TREE=/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0 IDE_BUILD_TREE=/home/uni/projects/3rdparties/qt-creator-opensource-4.14.0-x64-build

qmake_all: FORCE


all: Makefile ../../.local/share/data/QtProject/qtcreator/plugins/4.14.0/libCheatSh.so

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents i18n/cheatsh_ru.ts $(DISTDIR)/
	$(COPY_FILE) --parents cheatsh_unix.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/qt/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents cheatshplugin.h cheatsh_global.h cheatshconstants.h cheatoutputplane.h cheatfilter.h optionspage.h progressreport.h querymanager.h settings.h optionsdialog.h updatechecker.h $(DISTDIR)/
	$(COPY_FILE) --parents cheatshplugin.cpp cheatoutputplane.cpp cheatfilter.cpp optionspage.cpp progressreport.cpp querymanager.cpp settings.cpp optionsdialog.cpp updatechecker.cpp $(DISTDIR)/
	$(COPY_FILE) --parents optionsdialog.ui $(DISTDIR)/
	$(COPY_FILE) --parents i18n/cheatsh_ru.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) ../../.local/share/data/QtProject/qtcreator/plugins/4.14.0/$(TARGET) 
	-$(DEL_FILE) .qmake.stash /home/uni/projects/cheatsh-qtcreator/CheatSh.json
	-$(DEL_FILE) Makefile


####### Sub-libraries

ANSIEsc2HTML: FORCE
	echo Building ANSIEsc2HTML... ; cd /home/uni/projects/cheatsh-qtcreator/ANSIEsc2HTML ; /usr/bin/qmake CONFIG+=release ; make ; echo Done building ANSIEsc2HTML.

extraclean:
	cd /home/uni/projects/cheatsh-qtcreator/ANSIEsc2HTML ; make clean

clean: extraclean

extradistclean:
	cd /home/uni/projects/cheatsh-qtcreator/ANSIEsc2HTML ; make distclean

distclean: extradistclean

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_lrelease_make_all: cheatsh_ru.qm
compiler_lrelease_clean:
	-$(DEL_FILE) cheatsh_ru.qm
cheatsh_ru.qm: i18n/cheatsh_ru.ts
	/usr/bin/lrelease i18n/cheatsh_ru.ts -qm /home/uni/projects/cheatsh-qtcreator/i18n/cheatsh_ru.qm

compiler_rcc_make_all: .rcc/qrc_cheatsh_unix.cpp
compiler_rcc_clean:
	-$(DEL_FILE) .rcc/qrc_cheatsh_unix.cpp
.rcc/qrc_cheatsh_unix.cpp: cheatsh_unix.qrc \
		/usr/bin/rcc \
		i18n/cheatsh_ru.qm \
		images/settingscategory_cheatsh.png
	/usr/bin/rcc -name cheatsh_unix cheatsh_unix.qrc -o .rcc/qrc_cheatsh_unix.cpp

compiler_moc_predefs_make_all: .moc/release-shared/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) .moc/release-shared/moc_predefs.h
.moc/release-shared/moc_predefs.h: /usr/lib/qt/mkspecs/features/data/dummy.cpp
	g++ -pipe -Wno-noexcept-type -O2 -std=gnu++1z -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wextra -dM -E -o .moc/release-shared/moc_predefs.h /usr/lib/qt/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: .moc/release-shared/moc_cheatshplugin.cpp .moc/release-shared/moc_cheatoutputplane.cpp .moc/release-shared/moc_cheatfilter.cpp .moc/release-shared/moc_optionspage.cpp .moc/release-shared/moc_progressreport.cpp .moc/release-shared/moc_querymanager.cpp .moc/release-shared/moc_optionsdialog.cpp .moc/release-shared/moc_updatechecker.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) .moc/release-shared/moc_cheatshplugin.cpp .moc/release-shared/moc_cheatoutputplane.cpp .moc/release-shared/moc_cheatfilter.cpp .moc/release-shared/moc_optionspage.cpp .moc/release-shared/moc_progressreport.cpp .moc/release-shared/moc_querymanager.cpp .moc/release-shared/moc_optionsdialog.cpp .moc/release-shared/moc_updatechecker.cpp
.moc/release-shared/moc_cheatshplugin.cpp: cheatshplugin.h \
		settings.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/extensionsystem/iplugin.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/extensionsystem/extensionsystem_global.h \
		.moc/release-shared/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/uni/projects/cheatsh-qtcreator/.moc/release-shared/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/uni/projects/cheatsh-qtcreator -I/home/uni/projects/cheatsh-qtcreator/ANSIEsc2HTML/src -I/home/uni/projects/3rdparties/qt-creator-opensource-4.14.0-x64-build/src -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/src -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/src/libs -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/tools -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/src/plugins -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/src/libs -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/src/libs/3rdparty -I/usr/include/KF5/KSyntaxHighlighting -I/home/uni/projects/cheatsh-qtcreator -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtConcurrent -I/usr/include/qt/QtCore -I/usr/include/c++/9.3.0 -I/usr/include/c++/9.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/9.3.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include-fixed -I/usr/include cheatshplugin.h -o .moc/release-shared/moc_cheatshplugin.cpp

.moc/release-shared/moc_cheatoutputplane.cpp: cheatoutputplane.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/ioutputpane.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/core_global.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/fancylineedit.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/utils_global.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/completinglineedit.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/id.h \
		.moc/release-shared/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/uni/projects/cheatsh-qtcreator/.moc/release-shared/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/uni/projects/cheatsh-qtcreator -I/home/uni/projects/cheatsh-qtcreator/ANSIEsc2HTML/src -I/home/uni/projects/3rdparties/qt-creator-opensource-4.14.0-x64-build/src -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/src -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/src/libs -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/tools -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/src/plugins -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/src/libs -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/src/libs/3rdparty -I/usr/include/KF5/KSyntaxHighlighting -I/home/uni/projects/cheatsh-qtcreator -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtConcurrent -I/usr/include/qt/QtCore -I/usr/include/c++/9.3.0 -I/usr/include/c++/9.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/9.3.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include-fixed -I/usr/include cheatoutputplane.h -o .moc/release-shared/moc_cheatoutputplane.cpp

.moc/release-shared/moc_cheatfilter.cpp: cheatfilter.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/locator/ilocatorfilter.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/core_global.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/id.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/utils_global.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/optional.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/3rdparty/optional/optional.hpp \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/icore.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/icontext.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/helpitem.h \
		.moc/release-shared/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/uni/projects/cheatsh-qtcreator/.moc/release-shared/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/uni/projects/cheatsh-qtcreator -I/home/uni/projects/cheatsh-qtcreator/ANSIEsc2HTML/src -I/home/uni/projects/3rdparties/qt-creator-opensource-4.14.0-x64-build/src -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/src -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/src/libs -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/tools -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/src/plugins -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/src/libs -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/src/libs/3rdparty -I/usr/include/KF5/KSyntaxHighlighting -I/home/uni/projects/cheatsh-qtcreator -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtConcurrent -I/usr/include/qt/QtCore -I/usr/include/c++/9.3.0 -I/usr/include/c++/9.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/9.3.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include-fixed -I/usr/include cheatfilter.h -o .moc/release-shared/moc_cheatfilter.cpp

.moc/release-shared/moc_optionspage.cpp: optionspage.h \
		settings.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/dialogs/ioptionspage.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/core_global.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/icon.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/utils_global.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/theme/theme.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/id.h \
		.moc/release-shared/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/uni/projects/cheatsh-qtcreator/.moc/release-shared/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/uni/projects/cheatsh-qtcreator -I/home/uni/projects/cheatsh-qtcreator/ANSIEsc2HTML/src -I/home/uni/projects/3rdparties/qt-creator-opensource-4.14.0-x64-build/src -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/src -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/src/libs -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/tools -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/src/plugins -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/src/libs -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/src/libs/3rdparty -I/usr/include/KF5/KSyntaxHighlighting -I/home/uni/projects/cheatsh-qtcreator -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtConcurrent -I/usr/include/qt/QtCore -I/usr/include/c++/9.3.0 -I/usr/include/c++/9.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/9.3.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include-fixed -I/usr/include optionspage.h -o .moc/release-shared/moc_optionspage.cpp

.moc/release-shared/moc_progressreport.cpp: progressreport.h \
		cheatshconstants.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/progressmanager/futureprogress.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/core_global.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/id.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/utils_global.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/progressmanager/progressmanager.h \
		.moc/release-shared/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/uni/projects/cheatsh-qtcreator/.moc/release-shared/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/uni/projects/cheatsh-qtcreator -I/home/uni/projects/cheatsh-qtcreator/ANSIEsc2HTML/src -I/home/uni/projects/3rdparties/qt-creator-opensource-4.14.0-x64-build/src -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/src -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/src/libs -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/tools -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/src/plugins -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/src/libs -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/src/libs/3rdparty -I/usr/include/KF5/KSyntaxHighlighting -I/home/uni/projects/cheatsh-qtcreator -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtConcurrent -I/usr/include/qt/QtCore -I/usr/include/c++/9.3.0 -I/usr/include/c++/9.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/9.3.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include-fixed -I/usr/include progressreport.h -o .moc/release-shared/moc_progressreport.cpp

.moc/release-shared/moc_querymanager.cpp: querymanager.h \
		.moc/release-shared/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/uni/projects/cheatsh-qtcreator/.moc/release-shared/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/uni/projects/cheatsh-qtcreator -I/home/uni/projects/cheatsh-qtcreator/ANSIEsc2HTML/src -I/home/uni/projects/3rdparties/qt-creator-opensource-4.14.0-x64-build/src -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/src -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/src/libs -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/tools -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/src/plugins -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/src/libs -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/src/libs/3rdparty -I/usr/include/KF5/KSyntaxHighlighting -I/home/uni/projects/cheatsh-qtcreator -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtConcurrent -I/usr/include/qt/QtCore -I/usr/include/c++/9.3.0 -I/usr/include/c++/9.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/9.3.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include-fixed -I/usr/include querymanager.h -o .moc/release-shared/moc_querymanager.cpp

.moc/release-shared/moc_optionsdialog.cpp: optionsdialog.h \
		.moc/release-shared/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/uni/projects/cheatsh-qtcreator/.moc/release-shared/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/uni/projects/cheatsh-qtcreator -I/home/uni/projects/cheatsh-qtcreator/ANSIEsc2HTML/src -I/home/uni/projects/3rdparties/qt-creator-opensource-4.14.0-x64-build/src -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/src -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/src/libs -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/tools -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/src/plugins -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/src/libs -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/src/libs/3rdparty -I/usr/include/KF5/KSyntaxHighlighting -I/home/uni/projects/cheatsh-qtcreator -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtConcurrent -I/usr/include/qt/QtCore -I/usr/include/c++/9.3.0 -I/usr/include/c++/9.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/9.3.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include-fixed -I/usr/include optionsdialog.h -o .moc/release-shared/moc_optionsdialog.cpp

.moc/release-shared/moc_updatechecker.cpp: updatechecker.h \
		.moc/release-shared/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/uni/projects/cheatsh-qtcreator/.moc/release-shared/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/uni/projects/cheatsh-qtcreator -I/home/uni/projects/cheatsh-qtcreator/ANSIEsc2HTML/src -I/home/uni/projects/3rdparties/qt-creator-opensource-4.14.0-x64-build/src -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/src -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/src/libs -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/tools -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/src/plugins -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/src/libs -I/home/uni/projects/3rdparties/qt-creator-opensource-src-4.14.0/src/libs/3rdparty -I/usr/include/KF5/KSyntaxHighlighting -I/home/uni/projects/cheatsh-qtcreator -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtConcurrent -I/usr/include/qt/QtCore -I/usr/include/c++/9.3.0 -I/usr/include/c++/9.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/9.3.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include-fixed -I/usr/include updatechecker.h -o .moc/release-shared/moc_updatechecker.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: .uic/ui_optionsdialog.h
compiler_uic_clean:
	-$(DEL_FILE) .uic/ui_optionsdialog.h
.uic/ui_optionsdialog.h: optionsdialog.ui \
		/usr/bin/uic
	/usr/bin/uic optionsdialog.ui -o .uic/ui_optionsdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_lrelease_clean compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

.obj/release-shared/cheatshplugin.o: cheatshplugin.cpp cheatshplugin.h \
		settings.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/extensionsystem/iplugin.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/extensionsystem/extensionsystem_global.h \
		cheatshconstants.h \
		cheatfilter.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/locator/ilocatorfilter.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/core_global.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/id.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/utils_global.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/optional.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/3rdparty/optional/optional.hpp \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/icore.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/icontext.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/helpitem.h \
		querymanager.h \
		cheatoutputplane.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/ioutputpane.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/fancylineedit.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/completinglineedit.h \
		optionspage.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/dialogs/ioptionspage.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/icon.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/theme/theme.h \
		updatechecker.h \
		cheatsh_global.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/actionmanager/actionmanager.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/coreconstants.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/actionmanager/command.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/hostosinfo.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/osspecificaspects.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/actionmanager/actioncontainer.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/editormanager/editormanager.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/idocument.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/editormanager/documentmodel.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/fileutils.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/editormanager/ieditor.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/textfileformat.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/editormanager/editorwindow.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/texteditor/texteditorconstants.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/texteditor/texteditor_global.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/texteditor/texteditor.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/texteditor/blockrange.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/texteditor/codeassist/assistenums.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/texteditor/indenter.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/textutils.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/linecolumn.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/texteditor/refactoroverlay.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/editormanager/ieditorfactory.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/mimetypes/mimetype.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/elidinglabel.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/link.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/uncommentselection.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/extensionsystem/pluginmanager.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/aggregation/aggregate.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/aggregation/aggregation_global.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/cppeditor/cppeditorconstants.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/locator/locatormanager.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/locator/locatorconstants.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/locator/locator.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/locator/commandlocator.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/parameteraction.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/release-shared/cheatshplugin.o cheatshplugin.cpp

.obj/release-shared/cheatoutputplane.o: cheatoutputplane.cpp cheatoutputplane.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/ioutputpane.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/core_global.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/fancylineedit.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/utils_global.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/completinglineedit.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/id.h \
		settings.h \
		ANSIEsc2HTML/src/ansi_esc2html.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/release-shared/cheatoutputplane.o cheatoutputplane.cpp

.obj/release-shared/cheatfilter.o: cheatfilter.cpp cheatfilter.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/locator/ilocatorfilter.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/core_global.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/id.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/utils_global.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/optional.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/3rdparty/optional/optional.hpp \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/icore.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/icontext.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/helpitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/release-shared/cheatfilter.o cheatfilter.cpp

.obj/release-shared/optionspage.o: optionspage.cpp optionspage.h \
		settings.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/dialogs/ioptionspage.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/core_global.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/icon.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/utils_global.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/theme/theme.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/id.h \
		optionsdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/release-shared/optionspage.o optionspage.cpp

.obj/release-shared/progressreport.o: progressreport.cpp progressreport.h \
		cheatshconstants.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/progressmanager/futureprogress.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/core_global.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/id.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/utils_global.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/progressmanager/progressmanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/release-shared/progressreport.o progressreport.cpp

.obj/release-shared/querymanager.o: querymanager.cpp querymanager.h \
		cheatshconstants.h \
		progressreport.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/progressmanager/futureprogress.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/core_global.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/id.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/utils_global.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/progressmanager/progressmanager.h \
		settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/release-shared/querymanager.o querymanager.cpp

.obj/release-shared/settings.o: settings.cpp settings.h \
		cheatshconstants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/release-shared/settings.o settings.cpp

.obj/release-shared/optionsdialog.o: optionsdialog.cpp optionsdialog.h \
		.uic/ui_optionsdialog.h \
		settings.h \
		cheatshconstants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/release-shared/optionsdialog.o optionsdialog.cpp

.obj/release-shared/updatechecker.o: updatechecker.cpp updatechecker.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/icore.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/core_global.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/icontext.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/plugins/coreplugin/helpitem.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/optional.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/3rdparty/optional/optional.hpp \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/id.h \
		../3rdparties/qt-creator-opensource-src-4.14.0/src/libs/utils/utils_global.h \
		cheatshconstants.h \
		settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/release-shared/updatechecker.o updatechecker.cpp

.obj/release-shared/qrc_cheatsh_unix.o: .rcc/qrc_cheatsh_unix.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/release-shared/qrc_cheatsh_unix.o .rcc/qrc_cheatsh_unix.cpp

.obj/release-shared/moc_cheatshplugin.o: .moc/release-shared/moc_cheatshplugin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/release-shared/moc_cheatshplugin.o .moc/release-shared/moc_cheatshplugin.cpp

.obj/release-shared/moc_cheatoutputplane.o: .moc/release-shared/moc_cheatoutputplane.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/release-shared/moc_cheatoutputplane.o .moc/release-shared/moc_cheatoutputplane.cpp

.obj/release-shared/moc_cheatfilter.o: .moc/release-shared/moc_cheatfilter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/release-shared/moc_cheatfilter.o .moc/release-shared/moc_cheatfilter.cpp

.obj/release-shared/moc_optionspage.o: .moc/release-shared/moc_optionspage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/release-shared/moc_optionspage.o .moc/release-shared/moc_optionspage.cpp

.obj/release-shared/moc_progressreport.o: .moc/release-shared/moc_progressreport.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/release-shared/moc_progressreport.o .moc/release-shared/moc_progressreport.cpp

.obj/release-shared/moc_querymanager.o: .moc/release-shared/moc_querymanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/release-shared/moc_querymanager.o .moc/release-shared/moc_querymanager.cpp

.obj/release-shared/moc_optionsdialog.o: .moc/release-shared/moc_optionsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/release-shared/moc_optionsdialog.o .moc/release-shared/moc_optionsdialog.cpp

.obj/release-shared/moc_updatechecker.o: .moc/release-shared/moc_updatechecker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/release-shared/moc_updatechecker.o .moc/release-shared/moc_updatechecker.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/lib/qtcreator/plugins || mkdir -p $(INSTALL_ROOT)/lib/qtcreator/plugins
	$(QINSTALL_PROGRAM) ../../.local/share/data/QtProject/qtcreator/plugins/4.14.0/$(TARGET) $(INSTALL_ROOT)/lib/qtcreator/plugins/$(TARGET)
	-$(STRIP) --strip-unneeded $(INSTALL_ROOT)/lib/qtcreator/plugins/$(TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/lib/qtcreator/plugins/$(TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/lib/qtcreator/plugins/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

